Add option for explicit chmod with atomic file write.
canonical/pebble pull request #111
Opened 2022-03-10 23:24 UTC by rwcarlsen

Fixes #80

2022-03-16 02:00 UTC, benhoyt requested changes
Thanks! Just a couple of minor things: one bug-fix (missing `err :=`) and request for a files-API specific test.

2022-03-16 15:43 UTC, rwcarlsen commented on internal/osutil/io.go
> +		fd.Chmod(perm)
Oops - fixed.

2022-03-16 15:44 UTC, rwcarlsen commented on internal/osutil/io_test.go
> +	p := filepath.Join(tmpdir, "foo")
done.

2022-03-16 15:44 UTC, rwcarlsen commented on internal/osutil/io_test.go
> +	err := osutil.AtomicWriteFile(p, []byte(""), 0777, osutil.AtomicWriteChmod)
done.

2022-03-16 20:59 UTC, benhoyt approved these changes
Great, thanks!

2022-04-19 19:37 UTC, rwcarlsen commented
Is this waiting on anything in particular?

2022-04-19 20:58 UTC, benhoyt commented
A Gustavo review. Though this is really a minor bug fix, not an API change, so I'd say we can probably push it through.

2022-04-19 23:05 UTC, merged

2022-04-19 23:05 UTC, benhoyt commented
Merged, thanks @rwcarlsen!