randutil: allow pseudo rng seeding by caller
canonical/pebble pull request #222
Opened 2023-05-18 15:55 UTC by flotter

The randutil package was promoted to the x-go library because it provides helper functions needed by multiple projects.

Feedback from https://github.com/canonical/x-go/pull/17 highlighted the need for seeding of the pseudo random dependent functions to be left to the user of randutil (the crypto/rand functions are unaffected). The reason is simply that the seeding requirements differ between use cases (and projects), and it should be the responsibility of the caller to supply the seed.

Example Usage:

prng := randutil.NewPseudoRand(nil)
:
tmpfile := prng.RandomString(12)
:
wait := prng.RandomDuration(time.Hour)

Apply the changes required to make Pebble use the new randutil api.

2023-05-18 15:57 UTC, flotter commented
Dear reviewers, for details on this PR please refer to: https://github.com/canonical/x-go/pull/22

This PR requires an update to pull in the required x-go commit once an agreement is in place. In the meantime, the impact of the changes can be seen in this PR.

2023-05-19 01:52 UTC, benhoyt approved these changes
Seems reasonable to me, dependent on https://github.com/canonical/x-go/pull/22 changes.

2023-05-21 22:19 UTC, hpidcock approved these changes

2023-05-29 13:54 UTC, niemeyer requested changes
This doesn't seem to agree with prior conversations we had on the topic or the review that was discussed on x-go. I have a call with Fred tomorrow, so I believe this will be addressed there.

2023-05-29 14:01 UTC, flotter commented
@niemeyer Yes, this will get an update after our chat tomorrow.

2023-09-21 09:45 UTC, flotter commented
I am going to close this PR for now. Some rework is needed on a proposal I made on the snapd side, which will allow change proposed in Pebble, x-go and Snapd to align. Until this happens, this PR is stuck, and for now I would rather remove this from the Pebble backlog.

2023-09-21 09:45 UTC, closed without merging