feat: make layers with label prefix "pebble-" reserved
canonical/pebble pull request #403
Opened 2024-04-01 02:44 UTC by IronCore864

2024-04-01 02:52 UTC, IronCore864 commented
Hi @benhoyt, I'm creating draft PR, I'm not sure if this is the right way to implement it:

In order to use `pebble-service-args` in `PlanManager.SetServiceArgs` after making `pebble-*` as reserved layer label, the function `SetServiceArgs` has to check if the returned err. 

`Layer.Validate()` currently returns only type `FormatError`, in this case, I'd have to check on the error message, something like `strings.Contains(err.Error(), "cannot use reserved layer label")`.

I think in Go, it is generally recommended to avoid relying on error messages and it's better to handle errors based on types, right? So in my draft I created another type `ReservedLabelError`, and in `SetServiceArgs` I ignore the error if it's this type.

Does this make sense?

2024-04-03 22:02 UTC, benhoyt requested changes
Looks good -- just some minor changes requested.

2024-04-06 06:12 UTC, IronCore864 commented on internals/plan/plan.go
> +	if strings.HasPrefix(layer.Label, "pebble-") {
Yes, it makes sense.

2024-04-08 04:23 UTC, benhoyt approved these changes

2024-04-08 04:25 UTC, merged