poc: a metrics module for pebble
canonical/pebble pull request #519
Opened 2024-11-13 09:11 UTC by IronCore864

A self-implemented metrics module for Pebble.

Binary size doesn't increase (no extra libs used), still ~7.8MB with `-trimpath -ldflags='-s -w'`.

Manual test:

```bash
$ curl localhost:8000/metrics
# HELP my_counter A simple counter
# TYPE my_counter counter
my_counter 1
```

Some basic unit test is added to make sure the functionalities work as expected and there is no deadlock issue.

Todo: investigate how the official Prometheus Golang client gathers basic metrics like CPU usage and stuff.

2024-11-14 01:23 UTC, IronCore864 commented
<img width="773" alt="Screenshot-counter" src="https://github.com/user-attachments/assets/83a4fcf2-6a20-4c11-876a-cb420fa34e74">
<img width="774" alt="Screenshot-gauge" src="https://github.com/user-attachments/assets/e9976832-2836-4167-af23-8f20e9ca7451">
<img width="774" alt="Screenshot-gauge" src="https://github.com/user-attachments/assets/af63e31b-3583-4c7b-88e0-991db4f3dc32">

2024-11-14 02:48 UTC, IronCore864 commented
Some investigation into the default metrics that come with the Prometheus Go client:

## 1 List of Metrics from Go `runtime/metrics`

c.a. 80 items.

- /cgo/go-to-c-calls:calls
- /cpu/*
- /gc/cycles/*
- /gc/gogc:percent
- /gc/gomemlimit:bytes
- /gc/heap/*
- /gc/limiter/last-enabled:gc-cycle
- /gc/pauses:seconds
- /gc/scan/*
- /gc/stack/starting-size:bytes
- /godebug/*
- /memory/*
- /sched/gomaxprocs:threads
- /sched/goroutines:goroutines
- /sched/latencies:seconds
- /sched/pauses/*
- /sync/mutex/wait/total:seconds

---

## 2 List of Default Metrics from `prometheus/client_golang`

c.a. 40 items.

- go_gc_duration_seconds{quantile="*"}
- go_gc_duration_seconds_sum
- go_gc_duration_seconds_count
- go_gc_gogc_percent
- go_gc_gomemlimit_bytes
- go_goroutines
- go_info{version="go1.23.1"}
- go_memstats_*
- go_sched_gomaxprocs_threads
- go_threads
- promhttp_metric_handler_requests_in_flight
- promhttp_metric_handler_requests_total{code="200"}
- promhttp_metric_handler_requests_total{code="500"}
- promhttp_metric_handler_requests_total{code="503"}

---

## 3 How Are the Default Metrics from `prometheus/client_golang` Fetched/Calculated

### 3.1 From `runtime` and `runtime/debug`

- go_goroutines
- go_threads
- go_gc_duration_seconds
- go_memstats_last_gc_time_seconds
- go_info

### 3.2 From `runtime.MemStats` with Some Calculations

- go_memstats_alloc_bytes
- go_memstats_alloc_bytes_total
- go_memstats_buck_hash_sys_bytes
- go_memstats_frees_total
- go_memstats_gc_sys_bytes
- go_memstats_heap_alloc_bytes
- go_memstats_heap_idle_bytes
- go_memstats_heap_inuse_bytes
- go_memstats_heap_objects
- go_memstats_heap_released_bytes
- go_memstats_heap_sys_bytes
- go_memstats_last_gc_time_seconds
- go_memstats_mallocs_total
- go_memstats_mcache_inuse_bytes
- go_memstats_mcache_sys_bytes
- go_memstats_mspan_inuse_bytes
- go_memstats_mspan_sys_bytes
- go_memstats_next_gc_bytes
- go_memstats_other_sys_bytes
- go_memstats_stack_inuse_bytes
- go_memstats_stack_sys_bytes
- go_memstats_sys_bytes

### 3.3 Directly from runtime/metrics but Go-Version-Dependant

- go_gc_gogc_percent
- go_gc_gomemlimit_bytes
- go_sched_gomaxprocs_threads

### 3.4 Prometheus-Related

- promhttp_metric_handler_requests_in_flight
- promhttp_metric_handler_requests_total{code="200"}
- promhttp_metric_handler_requests_total{code="500"}
- promhttp_metric_handler_requests_total{code="503"}

Self-processed.

2024-12-09 12:16 UTC, IronCore864 commented
According to the last spec review, the following changes have been made:

1. The identity type is renamed from "basicauth" to just "basic".
2. The username field in the basic identity is removed -- we can just use the name of the identity instead.
3. Adding a new access type "metrics".
4. Passwords are hashed using OpenSSL (_TODO_).

After the first round of refactoring, here are some results:

### 1 Baisc Identity Name with Special Characters

```bash
$ cat identity.yaml
identities:
    "bob:asdf":
        access: read
        basic:
            password: bar
$ ./pebble add-identities --from ./identity.yaml
error: identity "bob:asdf" invalid: identity name "bob:asdf" contains invalid characters (only
       alphanumeric, underscore, and hyphen allowed)
```

### 2 Baisc Identity without Username

```bash
$ cat identity.yaml
identities:
    bob:
        access: read
        basic:
            password: bar
ubuntu@primary:~/work/pebble2$ ./pebble add-identities --from ./identity.yaml
Added 1 new identity.
```

### 3 Basic Identity Type "metrics"

```bash
$ # access type: read
$ cat identity.yaml
identities:
    bob:
        access: read
        basic:
            password: bar
$ ./pebble add-identities --from ./identity.yaml
Added 1 new identity.
$ # open access is fine
$ curl -u bob:bar localhost:4000/v1/health
{"type":"sync","status-code":200,"status":"OK","result":{"healthy":true}}
$ # no access on the metrics endpoint
$ curl -u bob:bar localhost:4000/metrics
{"type":"error","status-code":401,"status":"Unauthorized","result":{"message":"access denied","kind":"login-required"}}
```

```bash
$ # access type: metrics
$ cat identity.yaml
identities:
    bob:
        access: metrics
        basic:
            password: bar
$ ./pebble update-identities --from ./identity.yaml
Updated 1 identity.
$ # open access is fine
$ curl -u bob:bar localhost:4000/v1/health
{"type":"sync","status-code":200,"status":"OK","result":{"healthy":true}}
$ # accessing metrics
$ curl -u bob:bar localhost:4000/metrics
# HELP my_counter Total number of something processed.
# TYPE my_counter counter
my_counter{operation=read,status=success} 11
my_counter{operation=write,status=success} 22
my_counter{operation=read,status=failed} 11
# HELP my_gauge Current value of something.
# TYPE my_gauge gauge
my_gauge{sensor=temperature} 28.12
$ # no access on other endpoints
$ curl -u bob:bar localhost:4000/v1/changes
{"type":"error","status-code":401,"status":"Unauthorized","result":{"message":"access denied","kind":"login-required"}}
```

```bash
$ # access type: admin
$ cat identity.yaml
identities:
    bob:
        access: admin
        basic:
            password: bar
$ ./pebble update-identities --from ./identity.yaml
Updated 1 identity.
$ # admin can read metrics
$ curl -u bob:bar localhost:4000/v1/metrics
# HELP my_counter Total number of something processed.
# TYPE my_counter counter
my_counter{operation=read,status=success} 176
my_counter{operation=write,status=success} 352
my_counter{operation=read,status=failed} 176
# HELP my_gauge Current value of something.
# TYPE my_gauge gauge
my_gauge{sensor=temperature} 24.48
```

_TODO_: hashing password.

2024-12-09 19:42 UTC, benhoyt commented on internals/overlord/state/state.go
> +	Basic  *marshalledBasicIdentity `json:"basi,omitempty"`
Just skimming through this PR (not reviewing it yet), but noticed this, so commenting before I forget: basi -> basic

2025-01-24 02:24 UTC, IronCore864 commented
Notes:

We need to handle the memory usage issue in the future, to make this easier, after discussion, we decided not to use a self-implemented Prometheus-like module to store the metrics centrally, but rather, store the metrics on existing structs like `serviceData` and `CheckInfo`. In the last commit, the service-related metrics are implemented on `serviceData`. Check-related metrics are to be implemented.

2025-01-24 10:35 UTC, IronCore864 commented
Taking some note before the holiday season:

Currently, the check metrics is only working when the check is successful. When it fails, both counters will be reset to 0 and never increase. Need more debugging.

2025-02-07 02:04 UTC, benhoyt requested changes
Several comments, most importantly the design of the Metric type and the WriteMetrics interface.

2025-02-07 02:04 UTC, benhoyt commented on internals/daemon/api_metrics.go
> +	w.Write([]byte(buffer.String()))
Do we need to handle the error here, and at least log it (we probably can't return an HTTP error at this point)?

2025-02-11 02:19 UTC, IronCore864 commented on internals/daemon/api_metrics.go
> +	w.WriteHeader(http.StatusOK)
I noticed that `api_files` has it explicitly. To be consistent with existing code, I'd like to keep this line.

2025-02-12 14:18 UTC, gruyaume reviewed
I was curious about this change listening to the mid-cycle roadmap presentation. Nobody asked for this review, please feel free to ignore it.

2025-02-12 14:18 UTC, gruyaume commented on go.mod
> +	github.com/GehirnInc/crypt v0.0.0-20230320061759-8cc1b52080c5
Is this package maintained? Are we confident about introducing it in every charm / pebble deployment out there?

2025-02-12 14:25 UTC, benhoyt commented on go.mod
> +	github.com/GehirnInc/crypt v0.0.0-20230320061759-8cc1b52080c5
It hasn't been recently changed, but the part of it we're using is small a straight-forward, and the algorithm being implemented is stable and well-documented ([SHA-crypt](https://www.akkadia.org/drepper/SHA-crypt.txt)). So I would say it's "stable" rather than "unmaintained". I'm actually contemplating vendoring this (the core part of it is only ~100 LoC). But open to other ideas/concerns too.

2025-02-12 14:27 UTC, benhoyt commented on go.mod
> +	github.com/GehirnInc/crypt v0.0.0-20230320061759-8cc1b52080c5
We've done some diligence on it, see https://github.com/canonical/pebble/pull/563#issuecomment-2635646862 for example.

2025-02-13 03:16 UTC, benhoyt requested changes
Mostly minor comments, though a few structural things. Main thing that needs discussion is whether the perform_check and recover_check counts are actually going to provide the monitoring we want -- let's discuss.

2025-02-13 03:16 UTC, benhoyt commented on internals/overlord/checkstate/manager_test.go
> +		{Name: "chk1", Startup: "enabled", Status: "up", Threshold: 3, PerformCheckCount: 2, RecoverCheckCount: 0},
Hmm, yes, we definitely shouldn't be getting these fields coming through here. In fact, we should either have an internal `checkInfo` (with the metrics fields) and an exported one `CheckInfo` without them, or we should explicitly set them to zero after we've made the copy in `Checks()` -- probably the latter is simplest.

For testing, we should call the `WriteMetrics` method with a fake `MetricsWriter` that just appends to a slice or something, and compare that. Or just use an OpenTelemetryWriter and compare the output -- I see you're already doing that for the services metrics.

2025-02-13 03:16 UTC, benhoyt commented on internals/overlord/servstate/handlers.go
> +	// Update current-s_e time if derived status is changing.
Search/replace issue?

2025-02-13 03:16 UTC, benhoyt commented on internals/overlord/servstate/handlers.go
> +		Comment:    "Indicates if the service is currently active (1) or not (0)",
Let's use the same phrasing here as for the checks one, so "Whether the service is..."

2025-02-13 03:16 UTC, benhoyt commented on internals/overlord/servstate/manager_test.go
> +	openTelemetryWriter := metrics.NewOpenTelemetryWriter(buf)
Nit: given it's clear from the context, how about just `writer := ...`?

2025-02-13 03:16 UTC, benhoyt commented on internals/overlord/servstate/manager_test.go
> +	c.Assert(metrics, testutil.Contains, "pebble_service_start_count{service=test1} 1")
Should we just assert on the entire output, for simplicity, and so we're testing the HELP and TYPE parts?

2025-02-13 03:16 UTC, benhoyt commented on internals/overlord/servstate/manager.go
> +	for _, service := range m.services {
It's probably best to make the order stable, so let's grab the service names into a slice and `sort.Strings` them before looping. Otherwise the order of `/v1/metrics` will change each time you refresh it, which is not ideal.

Similar for the checks `WriteMetrics`.

2025-02-13 03:16 UTC, benhoyt commented on internals/overlord/checkstate/manager.go
> +	for _, info := range m.checks {
Per similar comment on `ServiceManager.WriteMetrics`, let's sort by check name to ensure the output is stable.

2025-02-13 03:18 UTC, benhoyt commented
@IronCore864 Can you please update the PR description to match our new approach?

Also, it probably goes without saying, but let's be sure **not to merge** this before the underlying identities PR that this builds on (#563) is reviewed for security and merged.

2025-02-14 02:11 UTC, IronCore864 commented on internals/metrics/metrics_test.go
> +my_gauge{} 1
I did more research: If there is no label, there should not be brackets. If a metric must have a label like the ones we have, we can't set it without a label anyway. I will update the code and test accordingly.

2025-02-14 02:28 UTC, IronCore864 commented on internals/metrics/metrics_test.go
> +			expected: `# HELP no_comment_metric
It's possible to have no `# HELP` and no `# TYPE` lines for a metric. I will remove the `# HELP` line if there is no comment. However, since we will definitely have a type, I will make the `# TYPE` mandatory.

2025-02-14 02:38 UTC, IronCore864 commented on internals/overlord/checkstate/handlers.go
> +			m.incPerformCheckCount(config)
If we put it in the beginning right after `runCheck`, it's possible that there is no CheckInfo yet (`updateCheckInfo` is called later).

I agree `check_failure_count` (and maybe `check_success_count` as well, which was what we had in the first place in the spec) is more useful. In the spec review, we only decided to use perform/recover check count, because they coincided with the type of the change, which does not seem to be a strong argument now that I look at it again. It does not matter where the `runCheck` is called (`doPerformCheck` or `doRecoverCheck`), it should depend on the result of `runCheck`. I will update them to `check_failure_count` and `check_success_count`

Whether the check failed or succeeded: I accidentally forgot to add this metric. I will add it (`pebble_check_up{check=bar}`).

2025-02-16 23:33 UTC, benhoyt commented on internals/metrics/metrics.go
> +		panic("invalid metric type")
Nit: best to include the type number in the message:
```suggestion
		panic(fmt.Sprintf("invalid metric type %d", mt))
```

2025-02-16 23:33 UTC, benhoyt commented on internals/metrics/metrics.go
> +	io.WriteString(otw.w, m.Name)
Note that we're not checking errors here (but we are above). In this case that's actually okay given that we know the writer is a `bytes.Buffer` (which never fails), but for future-proofing and reliability, let's check each error here.

2025-02-16 23:33 UTC, benhoyt commented on internals/metrics/metrics.go
> +			fmt.Fprintf(otw.w, "%s=%q", label.key, label.value) // Use %q to quote values.
Ah, good catch that these are quoted.

2025-02-16 23:33 UTC, benhoyt commented on internals/overlord/checkstate/manager.go
> +	check, ok := m.checks[config.Name]
We should do this check in `incRecoverCheckCount` as well. Maybe we can have a little helper method `ensureCheck(name string) *CheckInfo` that does this dance, to avoid repeating it three times.

2025-02-17 01:41 UTC, IronCore864 commented on internals/metrics/metrics.go
> +	io.WriteString(otw.w, m.Name)
Got it, I will check all errors for all `io.WriteString` and `fmt.Fprintf` to the writer.

2025-02-18 03:22 UTC, IronCore864 commented on internals/overlord/checkstate/handlers.go
> +			m.incPerformCheckCount(config)
After discussing it with Ben, Tony, and Harry, we decided to use `pebble_check_success_count` and `pebble_check_failure_count` because they provide more insight than the previously decided `pebble_perform_check_count` and `pebble_recover_check_count`.

2025-02-18 04:30 UTC, IronCore864 commented
Check metrics updated, tests also updated.

2025-02-20 03:30 UTC, benhoyt commented on internals/daemon/api_metrics.go
> +	return metricsResponse{
I realise I've done this elsewhere (like the files API), but you can actually simplify and do a handler like inline with:

```go
return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
    func v1GetMetrics(c *Command, r *http.Request, _ *UserState) Response {
        ...
    }
}
```

2025-02-20 03:37 UTC, benhoyt commented on internals/metrics/metrics.go
> +	_, err = fmt.Fprintf(otw.w, " %d\n", m.ValueInt64)
For a human debugging the output, it would be nice to separate each comment+metric block with a blank line:
```suggestion
	_, err = fmt.Fprintf(otw.w, " %d\n\n", m.ValueInt64)
```

2025-02-20 03:39 UTC, benhoyt commented on internals/metrics/metrics.go
> +	TypeCounterInt MetricType = iota
It's probably worth doing `iota+1` so these start at one, so we don't accidentally forget to set `Type` and get the zero value (`TypeCounterInt`) by accident.

2025-02-20 03:40 UTC, benhoyt commented on internals/metrics/metrics.go
> +	_, err := fmt.Fprintf(otw.w, "# TYPE %s %s\n", m.Name, m.Type.String())
`.String()` is done for you by the `fmt` package when you use the `%s` verb:
```suggestion
	_, err := fmt.Fprintf(otw.w, "# TYPE %s %s\n", m.Name, m.Type)
```

2025-02-20 03:45 UTC, benhoyt commented on internals/overlord/checkstate/manager.go
> +type checkData struct {
Yeah, I think this separation makes things a lot cleaner now, thanks.

2025-02-20 03:45 UTC, benhoyt commented on internals/overlord/checkstate/manager.go
> +func (c *checkData) writeMetrics(writer metrics.Writer) error {
This should be singular:
```suggestion
func (c *checkData) writeMetric(writer metrics.Writer) error {
```

2025-02-20 03:48 UTC, benhoyt commented on internals/overlord/checkstate/manager.go
> +	if c.status == CheckStatusUp {
@tonyandrewmeyer I forget what we decided here, do you remember: should CheckStatusInactive mean the "up" metric report up (1) or down (0)? I was thinking it would be up.

2025-02-20 03:56 UTC, benhoyt commented on internals/overlord/checkstate/manager.go
> +		ValueInt64: checkUp,
I don't really care which way we do this (int64 here or above), but let's at least be consistent between checks and services (we're currently doing it int64-on-variable here and int64-on-field in services). Now that I see them I like the services way better, so let's change this to int64-on-field (this line).

2025-02-20 03:57 UTC, benhoyt commented on internals/overlord/servstate/handlers.go
> +func (d *serviceData) writeMetrics(writer metrics.Writer) error {
```suggestion
func (d *serviceData) writeMetric(writer metrics.Writer) error {
```

2025-02-20 04:50 UTC, tonyandrewmeyer commented on internals/overlord/checkstate/manager.go
> +	if c.status == CheckStatusUp {
I don't think we decided anything here - the discussion on this predated the start/stop work being completed, if I recall correctly.

When we combine checks together (e.g. for health determination) stopped checks are skipped - treated as if they don't exist. When we list checks or get information about a single check elsewhere, we don't have to have a binary choice, so we have up/down/inactive.

Here:
 * 0 (down) definitely seems wrong because it implies that the result of the check is that it's failing.
 * 1 (up) seems pretty wrong because it implies that the result of the check is success, even though we don't actually know - but it's a little better because it's the same effect for things like checking health
 * 2 or some other number meaning "inactive" doesn't seem great for a gauge type - I feel like gauge values ought to be actual numbers rather than enums.

I think the most correct behaviour would be to not list any inactive checks, because they don't have an up or down status. This is like health: they are the same as if they didn't exist.

For the other check metrics, check_success_count, check_failure_count, having inactive checks makes sense (and we did adjust the start/stop code so that the check-info failure count is preserved for inactive checks, so having the metric available is consistent).

2025-02-20 07:52 UTC, benhoyt commented on internals/overlord/checkstate/manager.go
> +	if c.status == CheckStatusUp {
> I think the most correct behaviour would be to not list any inactive checks, because they don't have an up or down status. This is like health: they are the same as if they didn't exist.

Ah yes, that's definitely what we should do -- exclude them from /v1/metrics altogether.

@IronCore864 Let's do that. It would have to be checked in the `WriteMetrics` loop.

2025-02-20 08:23 UTC, IronCore864 commented on internals/overlord/checkstate/manager.go
> +	if c.status == CheckStatusUp {
I agree using gauge like it's an enum doesn't feel right. I will choose to not report pebble_check_up for inactive checks.

2025-02-25 21:33 UTC, benhoyt requested changes
This looks really good now, thanks. I've left some (minor) comments.

In addition, I think this probably needs to be highlighted a bit more in our docs. Maybe a new section with example output at https://documentation.ubuntu.com/pebble/how-to/run-services-reliably/? What do you think, @dwilding?

2025-02-25 21:33 UTC, benhoyt commented on docs/specs/openapi.yaml
> +        This endpoint requires HTTP basic authentication using an identity of type "basic". See [Identities](../identities) for more information.
```suggestion
        When used over TCP, this endpoint requires HTTP basic authentication using an identity of type "basic". See [Identities](../identities) for more information.
```

2025-02-25 21:33 UTC, benhoyt commented on internals/metrics/metrics.go
> +		panic(fmt.Sprintf("invalid metric type %d", mt))
```suggestion
		panic(fmt.Sprintf("internal error: invalid metric type %d", mt))
```

2025-02-25 21:33 UTC, benhoyt commented on internals/metrics/metrics_test.go
> +func (s *OpenTelemetryWriterSuite) TestOpenTelemetryWriter(c *C) {
Nit: because this is in `OpenTelemetryWriterSuite`, the test name can just be `TestWriter`:
```suggestion
func (s *OpenTelemetryWriterSuite) TestWriter(c *C) {
```

2025-02-25 21:33 UTC, benhoyt commented on internals/overlord/checkstate/manager.go
> +// checkData holds the metrics and other data for a a single check.
```suggestion
// checkData holds the metrics and other data for a single check.
```

2025-02-25 21:33 UTC, benhoyt commented on internals/overlord/checkstate/manager.go
> +	// Not to list any inactive checks because they don't have an up or down status.
```suggestion
	// Don't list any inactive checks because they don't have an up or down status.
```

2025-02-25 21:33 UTC, benhoyt commented on internals/overlord/checkstate/manager_test.go
> +pebble_check_success_count{check="chk1"} 2
Hmm, this is racy. If CI is slow and the check (which has a short period) runs 3 or 4 times, this will fail. The simplest way I can think of is using a regex to match , with `\d+` in this position. (I think any number, even 1 here, would be okay. I don't think there's a specific reason we need to wait for it to run twice.)

2025-02-25 21:33 UTC, benhoyt commented on internals/overlord/checkstate/manager_test.go
> +		if len(b) >= 2 {
See below -- could just wait for >= 1

2025-02-25 21:33 UTC, benhoyt commented on internals/overlord/checkstate/manager_test.go
> +pebble_check_failure_count{check="chk1"} 2
I believe this is racy for the same reason as above.

2025-02-25 21:33 UTC, benhoyt commented on internals/overlord/servstate/handlers.go
> +	active := 0
It won't affect the metrics, but it would be nice to move the `pebble_service_active` metric to the top of `writeMetric` so that it's in the same position as the `pebble_check_up` gauge (top). It feels odd that this status gauge is last but the checks one is first. I think putting them both first is best.

2025-02-26 01:54 UTC, IronCore864 commented
> In addition, I think this probably needs to be highlighted a bit more in our docs. Maybe a new section with example output at https://documentation.ubuntu.com/pebble/how-to/run-services-reliably/? What do you think, @dwilding?

I discussed this with David and we agreed on the following outline:

```
Intro

## Use HTTP health checks

## Restart a service when the health check fails

## Access health metrics in OpenMetrics format

... This would explain how to create an identity and show a curl example of how to access metrics. Then link to somewhere about configuring Prometheus.

## Limitations of health checks

## See more
```

I will work on this in the same PR.

2025-02-26 02:29 UTC, IronCore864 commented
"How to run services reliably" updated, preview: https://canonical-ubuntu-documentation-library--519.com.readthedocs.build/pebble/how-to/run-services-reliably/#access-health-metrics-in-openmetrics-format.

2025-02-26 02:39 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +To allow accessing the metrics endpoint with HTTP basic authentication, create a "basic" type identity and give it "metrics" access. Prepare this file:
```suggestion
To access the metrics endpoint with HTTP basic authentication, first create a "basic" type identity and give it "metrics" access. Prepare this file:
```

2025-02-26 02:40 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +If we run Pebble with the `--http` option, Pebble exposes the `/v1/metrics` endpoint over HTTP, providing metrics data in [OpenMetrics](https://github.com/prometheus/OpenMetrics) format. This endpoin
Could drop the mention of open-access if you like:
```suggestion
If we run Pebble with the `--http` option, Pebble exposes the `/v1/metrics` endpoint over HTTP, providing metrics data in [OpenMetrics](https://github.com/prometheus/OpenMetrics) format. This endpoint and requires HTTP basic authentication.
```

2025-02-26 02:43 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +To access the metrics endpoint, make sure we run Pebble with the `--http` option: `pebble run --http=:4000`, then we can get the metrics data with HTTP basic authentication:
I think we could shorten this to make the instructions more obvious:
```suggestion
To access the metrics endpoint, run `pebble run --http=:4000`, then use `curl` and specify the identity that we created:
```

2025-02-26 02:45 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +To configure Prometheus to scrape a target protected by HTTP basic authentication, add an `http_config` section in the `scrape_config`. Read more [here in the official documentation](https://promethe
Recommend adjusting the link:
```suggestion
To configure Prometheus to scrape a target protected by HTTP basic authentication, add an `http_config` section in the `scrape_config`. See the [Prometheus configuration documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config).
```

2025-02-26 20:07 UTC, benhoyt commented
Looks good to me, thanks! I've tested this a bit locally too. Merging now so I can include this in today's release.

2025-02-26 20:07 UTC, benhoyt approved these changes

2025-02-26 20:07 UTC, merged