Docs: how to run services reliably and update service autorestart to service lifecycle.
canonical/pebble pull request #541
Opened 2024-12-22 04:50 UTC by IronCore864

2024-12-24 03:45 UTC, dwilding commented
Thank you for doing this! Before I work on a more detailed review, I have a few ideas about the overall contents:

1. **"Health checks" section** - I think this section should have more prominence. So how about making each topic a separate subsection, instead of using bullets?

    Also in this section, I think we ought to make it obvious up-front that "health checks" are a combination of Pebble's feature + what the service author chooses to implement.

    Then within each topic we can say what we recommend the service to do. For example, in the topic "Identifying Dependent Service Failures", I really like what you wrote:

    > A service’s health check can include checks to ensure it can connect to its database, message queue, or other required services.

    This is nice & clear advice about how to approach health checks on the service side.

2. **"Configuring health checks in Pebble" and "Restarting service on health check failure" sections** - I'd probably combine these into a single section that is fully focused on how to configure a health check of HTTP type and restart the service when the health check fails.

    Since this is a how-to doc, it's OK to omit the different options for health checks. I think it's better to give a specific scenario, then link to the reference pages for people to understand the different options.

3. **"Demo service" and "Putting it all together" sections** - I feel these are extremely helpful, and the `health-check-sample-service` idea is neat! Since these sections are more guided, I'd consider moving them to a tutorial instead.

2024-12-31 00:30 UTC, IronCore864 commented
> Thank you for doing this! Before I work on a more detailed review, I have a few ideas about the overall contents:
> 
> 1. **"Health checks" section** - I think this section should have more prominence. So how about making each topic a separate subsection, instead of using bullets?
>    Also in this section, I think we ought to make it obvious up-front that "health checks" are a combination of Pebble's feature + what the service author chooses to implement.
>    Then within each topic we can say what we recommend the service to do. For example, in the topic "Identifying Dependent Service Failures", I really like what you wrote:
>    > A service’s health check can include checks to ensure it can connect to its database, message queue, or other required services.
>    
>    
>    This is nice & clear advice about how to approach health checks on the service side.
> 2. **"Configuring health checks in Pebble" and "Restarting service on health check failure" sections** - I'd probably combine these into a single section that is fully focused on how to configure a health check of HTTP type and restart the service when the health check fails.
>    Since this is a how-to doc, it's OK to omit the different options for health checks. I think it's better to give a specific scenario, then link to the reference pages for people to understand the different options.
> 3. **"Demo service" and "Putting it all together" sections** - I feel these are extremely helpful, and the `health-check-sample-service` idea is neat! Since these sections are more guided, I'd consider moving them to a tutorial instead.

Refactored according to 1 and 2; for 3, I haven't done anything yet, mostly because those two parts are not long enough for a tutorial. Should we do that anyway?

2025-01-02 02:52 UTC, IronCore864 commented
Per discussion elsewhere, we decided to remove the "Demo service" and "Putting it all together" sections. We will add a tutorial in the future using content from these sections.

2025-01-03 01:54 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +### More on health checks
I'd recommend breaking this out as a separate section and moving it to the end of the doc. We could call it "Limitations of health checks"

2025-01-03 02:27 UTC, dwilding commented
Looking at "How to run services reliably" with fresh eyes, I think we should go further in refactoring the doc to make the actionable info stand out. I recommend that we drop "Service reliability in the modern microservice world" as a separate section, keeping the info as context within the section that follows.

The nature of this topic is going to require some explanatory content, but I think we can compress it down somewhat.

I've taken what you wrote and put together this structure - what do you think?

```
# How to run services reliably

You can use Pebble's [health checks](../reference/health-checks) feature to perform checks on services and restart services if the checks fail. To use health checks effectively, you should consider:

- How services monitor their own health and make that information available to Pebble
- How Pebble is configured to fetch health information and respond to unhealthy services

This guide demonstrates how to use health checks to address common service reliability challenges.

## Return health information from services

As you implement health checks within services, consider typical causes of unreliability. You can monitor for unhealthy conditions and expose that information for Pebble to consume.

A common way to expose health information is to use an HTTP endpoint. For an example of how to configure Pebble to check an HTTP endpoint, see [](run_services_reliably_use_http_checks).

### Detect resource exhaustion

A single microservice consuming excessive resources (CPU, memory, disk I/O, and so on) can impact not only its performance and availability but also potentially affect other services depending on it.

Recommendation: Implement a health check that signals an unhealthy state if resource consumption exceeds predefined thresholds.

### Identify dependent service failures

_Use a similar structure of brief context followed by recommendations_

<!-- more subsections here -->

(run_services_reliably_use_http_checks)=
## Use HTTP-based health checks in Pebble

<!-- details here -->
```

2025-01-03 03:25 UTC, dwilding commented on docs/reference/service-lifecycle.md
> +Pebble manages the lifecycle of a service, including starting, stopping, and restarting it, with a focus on handling health checks and failures, and implementing auto-restart with backoff strategies,
This sentence is quite long. Would it be possible to split it? Something like this:
```suggestion
Pebble manages the lifecycle of a service, including starting, stopping, and restarting it. Pebble also handles health checks, failures, and auto-restart with backoff. This is all achieved using a state machine with the following states:
```

2025-01-03 03:28 UTC, dwilding commented on docs/reference/service-lifecycle.md
> +If the service exits quickly, the started channel receives an error. The error, along with the last logs, are added to the task (see more in [Changes and tasks](/reference/changes-and-tasks.md)). Thi
What does "started channel" refer to?

2025-01-03 03:34 UTC, dwilding commented on docs/reference/service-lifecycle.md
> +This is done whether the exit code is zero or non-zero, but you can fine-tune the behaviour using the `on-success` and `on-failure` fields in a configuration layer. The possible values for these fiel
The first paragraph is a nice summary of the behaviour - I think it will stick in my head :smile: 

I have a small suggestion for the second paragraph, as "This is done whether the exit code is zero or non-zero" could be misread as meaning something happens regardless of whether the exit code is zero or non-zero.

```suggestion
By default, Pebble's service manager automatically restarts services that exit unexpectedly, regardless of whether the service is in the "starting" state (the `okayDelay` period has not passed) or in the "running" state (`okayDelay` has passed, and the service is considered to be "running").

Pebble considers a service to have exited unexpectedly if the exit code is non-zero. You can fine-tune the behaviour using the `on-success` and `on-failure` fields in a configuration layer. The possible values for these fields are:
```

2025-01-03 03:41 UTC, dwilding commented on docs/reference/service-lifecycle.md
> +For example, with default settings for the above configuration, in `restart` mode, the first time a service exits, Pebble waits for half a second. If the service exits again, Pebble calculates the ne
Very minor - we can drop "for example" to help with making the sentence shorter. (This part is a description of the default behaviour, so I think it's fine to not say "for example")
```suggestion
With default settings for the above configuration, in `restart` mode, the first time a service exits, Pebble waits for half a second. If the service exits again, Pebble calculates the next backoff delay by multiplying the current delay by `backoff-factor`, which results in a 1-second delay. The next delay will be 2 seconds, then 4 seconds, and so on, capped at 30 seconds.
```

2025-01-03 03:56 UTC, dwilding commented
I've finished adding comments on specific parts. There's a main refactoring suggestion [here](https://github.com/canonical/pebble/pull/541#issuecomment-2568619930).

2025-01-04 05:07 UTC, IronCore864 commented on docs/reference/service-lifecycle.md
> +If the service exits quickly, the started channel receives an error. The error, along with the last logs, are added to the task (see more in [Changes and tasks](/reference/changes-and-tasks.md)). Thi
This is a bit too deep into the code, I will rephrase this.

2025-01-04 05:14 UTC, IronCore864 commented
> Looking at "How to run services reliably" with fresh eyes, I think we should go further in refactoring the doc to make the actionable info stand out. I recommend that we drop "Service reliability in the modern microservice world" as a separate section, keeping the info as context within the section that follows.
> 
> The nature of this topic is going to require some explanatory content, but I think we can compress it down somewhat.
> 
> I've taken what you wrote and put together this structure - what do you think?
> 
> ```
> # How to run services reliably
> 
> You can use Pebble's [health checks](../reference/health-checks) feature to perform checks on services and restart services if the checks fail. To use health checks effectively, you should consider:
> 
> - How services monitor their own health and make that information available to Pebble
> - How Pebble is configured to fetch health information and respond to unhealthy services
> 
> This guide demonstrates how to use health checks to address common service reliability challenges.
> 
> ## Return health information from services
> 
> As you implement health checks within services, consider typical causes of unreliability. You can monitor for unhealthy conditions and expose that information for Pebble to consume.
> 
> A common way to expose health information is to use an HTTP endpoint. For an example of how to configure Pebble to check an HTTP endpoint, see [](run_services_reliably_use_http_checks).
> 
> ### Detect resource exhaustion
> 
> A single microservice consuming excessive resources (CPU, memory, disk I/O, and so on) can impact not only its performance and availability but also potentially affect other services depending on it.
> 
> Recommendation: Implement a health check that signals an unhealthy state if resource consumption exceeds predefined thresholds.
> 
> ### Identify dependent service failures
> 
> _Use a similar structure of brief context followed by recommendations_
> 
> <!-- more subsections here -->
> 
> (run_services_reliably_use_http_checks)=
> ## Use HTTP-based health checks in Pebble
> 
> <!-- details here -->
> ```

I haven't done this refactor yet because it seems to be a very significant rework. I have given it some thought, and the current logic is:

First, introduce a health check. Then, explain in what scenarios it's helpful, which leads to Pebble's health check feature, how to configure it, and why it can help improve reliability. In this way, we could paint a picture, which I think a how-to guide should do: what exact problems this document can help achieve.

The suggested logic focuses more on Pebble and its features without laying too much background information first, which then is intertwined with the following paragraphs. This was less clear to me, so I hesitated about the refactoring. Maybe we should get more input from @benhoyt.

Other suggestions are all adopted.

2025-01-06 04:55 UTC, dwilding commented
It also sounds good to me if we wait to get Ben's input. If we end up not doing the refactoring, the part that I feel needs to be most emphasized somewhere is that "health checks" are a combination of:
- How services monitor their own health and make that information available to Pebble
- How Pebble is configured to fetch health information and respond to unhealthy services
I think this distinction is important context for the advice in the doc.

2025-01-21 05:54 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +## Using health checks of the HTTP type
Suggestion for consistency with headings in other how-tos:

```suggestion
## Use health checks of the HTTP type
```

2025-01-21 05:54 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +### Configuring HTTP-type health checks
```suggestion
### Configure HTTP-type health checks
```

2025-01-21 05:54 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +### Restarting the service when the health check fails
```suggestion
### Restart the service when the health check fails
```

2025-01-21 05:58 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +        period: 30s
Was this supposed to be 10s?

2025-01-21 05:59 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +For example, to configure a health check of HTTP type named `svc1-up` checking the endpoint `http://127.0.0.1:5000/health` at a 10-second interval with a timeout of 3 second and threshold of 3, we ca
Since we're explaining below what period, timeout, and threshold mean, I wouldn't repeat it here. How about this:

```suggestion
For example, we can configure a health check of HTTP type named `svc1-up` that checks the endpoint `http://127.0.0.1:5000/health`:
```

2025-01-21 06:01 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +- `threshold`: After how many consecutive errors (defaults to 3) is the check considered "down"
Adding periods for consistency:

```suggestion
- `timeout`: If the check hasn't responded before the timeout (defaults to 3 seconds), consider the check an error.
- `threshold`: After how many consecutive errors (defaults to 3) is the check considered "down".
```

2025-01-21 06:33 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +Note that although health checks are useful, they are not a complete solution for reliability and has their own limitations: Health checks can detect issues like connection to a database due to netwo
Suggestions for readability:

```suggestion
Although health checks are useful, they are not a complete solution for reliability:
- Health checks can detect issues such as a failed database due to network issues, but they can't fix the network issue itself.
- Health checks also can't replace testing and monitoring.
- Health checks shouldn't be used for scheduling tasks like backups.
```

2025-01-21 06:40 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +To make the managed services more reliable, Pebble provides a comprehensive health check feature.
For a topic like health checks, I think this context is useful, to give some inspiration about how heath checks could be applied in practice (since we can't tell people exactly what or what not to implement). To help with readability, I recommend some edits:

```suggestion
Microservice architectures offer flexibility, but they can introduce reliability challenges such as network interruptions, resource exhaustion, problems with dependent services, cascading failures, and deployment issues. Health checks can address these issues by monitoring resource usage, checking the availability of dependencies, catching problems of new deployments, and preventing downtime by redirecting traffic away from failing services.

To help you manage services more reliably, Pebble provides a comprehensive health check feature.
```

2025-01-21 06:43 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +- [How to manage service dependencies](service-dependencies)
Is it so necessary to include "How to manage service dependencies" in the list? It doesn't seem directly applicable, and it's already visible in the navigation menu.

2025-01-21 06:45 UTC, dwilding approved these changes
I've finished reviewing. I think this update keeps the key context and makes the whole doc more approachable - good job :slightly_smiling_face:

2025-01-24 02:12 UTC, benhoyt requested changes
This looks good! Requesting some minor changes, but I'm happy with the structure.

I think it'd be good to move the "service autorestart" -> "service lifecycle" changes to a separate PR for separate review. It'll also mean we can check off the "Pebble how-tos" roadmap item sooner. :-)

2025-01-24 02:12 UTC, benhoyt commented on docs/how-to/run-services-reliably.md
> +The health check is considered successful if the check returns an HTTP 200 response. After getting a certain number of failures in a row, the health check is considered "down" (or unhealthy).
This is actually 2xx (see also [this minor issue I just fixed](https://github.com/canonical/pebble/pull/565)).
```suggestion
The health check is considered successful if the URL returns any HTTP 2xx response. After getting a certain number of failures in a row, the health check is considered "down" (or unhealthy).
```

2025-01-24 02:12 UTC, benhoyt commented on docs/how-to/run-services-reliably.md
> +### Configure HTTP-type health checks
I don't think this heading adds anything. I reckon we should drop it.

2025-01-24 02:12 UTC, benhoyt commented on docs/how-to/run-services-reliably.md
> +For example, we can configure a health check of HTTP type named `svc1-up` that checks the endpoint `http://127.0.0.1:5000/health`:
```suggestion
For example, we can configure a health check of type `http` named `svc1-up` that checks the endpoint `http://127.0.0.1:5000/health`:
```

2025-01-24 02:12 UTC, benhoyt commented on docs/how-to/run-services-reliably.md
> +    threshold: 3
It seems odd to specify these if we set them to the defaults. You already mention the defaults below. How about this:

```suggestion
    period: 5s    # default 10s
    timeout: 1s   # default 3s
    threshold: 5  # default 3
```

2025-01-24 02:12 UTC, benhoyt commented on docs/how-to/run-services-reliably.md
> +- `timeout`: If the check hasn't responded before the timeout (defaults to 3 seconds), consider the check an error.
I think this reads a bit oddly with the parenthesized default in the middle:
```suggestion
- `timeout`: If the check hasn't responded before the timeout, consider the check an error (defaults to 3 seconds).
```

2025-01-24 02:12 UTC, benhoyt commented on docs/how-to/run-services-reliably.md
> +- `threshold`: After how many consecutive errors (defaults to 3) is the check considered "down".
```suggestion
- `threshold`: After this many consecutive errors the check considered "down"  (defaults to 3).
```

2025-01-24 02:12 UTC, benhoyt commented on docs/how-to/run-services-reliably.md
> +Given the default values, a minimum check looks like the following:
```suggestion
If we're happy with the default values, a minimum check looks like the following:
```

2025-01-24 02:12 UTC, benhoyt commented on docs/how-to/run-services-reliably.md
> +Besides the HTTP type, there are two more health check types in Pebble: `tcp`, which opens the given TCP port, and `exec`, which executes a user-specified command. For more information, see [Health c
```suggestion
Besides the `http` type, there are two more health check types in Pebble: `tcp`, which opens the given TCP port, and `exec`, which executes a user-specified command. For more information, see [Health checks](../reference/health-checks) and [Layer specification](../reference/layer-specification).
```

2025-01-24 02:12 UTC, benhoyt commented on docs/how-to/run-services-reliably.md
> +### Restart the service when the health check fails
Because this applies to any check type, I think this should be a H2 header:
```suggestion
## Restart a service when the health check fails
```

2025-01-24 02:12 UTC, benhoyt commented on docs/how-to/run-services-reliably.md
> +- Health checks shouldn't be used for scheduling tasks like backups.
```suggestion
- Health checks shouldn't be used for scheduling tasks like backups. Use a cron-style tool for that.
```

2025-01-24 02:12 UTC, benhoyt commented on docs/how-to/run-services-reliably.md
> +- `timeout`: If the check hasn't responded before the timeout (defaults to 3 seconds), consider the check an error.
Or we could just drop these, if we add the `# default 10s` style comments in the YAML above.

2025-01-24 02:29 UTC, IronCore864 commented on docs/how-to/run-services-reliably.md
> +- `timeout`: If the check hasn't responded before the timeout (defaults to 3 seconds), consider the check an error.
A comment in the first example is probably more than enough. I will add comments and drop this list.

2025-01-24 02:48 UTC, benhoyt approved these changes
Thanks!

2025-01-24 04:35 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +- `threshold`: After this many consecutive errors the check considered "down".
```suggestion
- `threshold`: After this many consecutive errors, the check is considered "down".
```

2025-01-24 04:38 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +- Health checks shouldn't be used for scheduling tasks like backups. Use a cron-style tool for that.
Very minor, but I'd recommend "such as" instead of "like":

```suggestion
- Health checks shouldn't be used for scheduling tasks such as backups. Use a cron-style tool for that.
```

2025-01-24 04:42 UTC, dwilding commented on docs/how-to/run-services-reliably.md
> +The health check is considered successful if the URL returns any HTTP 2xx response. After getting a certain number of failures in a row, the health check is considered "down" (or unhealthy).
A small thing, but I think we should change "failures" to "errors", to match the term used in the bullet points about `timeout` and `threshold`. Later in the doc we use "failure" to mean the check is down, so it could be confusing to use it here with a different meaning.

```suggestion
The health check is considered successful if the URL returns any HTTP 2xx response. After getting a certain number of errors in a row, the health check is considered "down" (or unhealthy).
```

2025-01-24 06:30 UTC, merged